### ISSUE TITLE
Actionbar debug message

### ISSUE THREAD

**Issue by StealWonders** [RypoFalem/ArmorStandEditor#19]
When using the plugin the server shows people who have access to see admin messages the following: 

![](https://i.stealwonders.de/javaw_WWZvja2Nyx.png)

This used to not be the case. I had a quick look at the code and the cause of this is that the plugin is executing the /title or action bar command which can simply be replaced by an internal Bukkit method. I believe it's player.sendActionbar() or similar.

**Comment by RoboMWM** [comment]
That method is in Paper, with an uglier equivalent in spigot. Unsure if in CB.

You can mute it with a gamerule

**Comment by StealWonders** [comment]
I don't want to mute the gamerule as I need it.

**Comment by Puremin0rez** [comment]
I've submitted a PR to resolve this: #23

**Comment by RypoFalem** [comment]
#23 merged. Thanks :)
