### ISSUE TITLE
Gravity not working

### ISSUE THREAD

**Issue by MagpieTear** [RypoFalem/ArmorStandEditor#20]
Multiple users on a paper server experiencing an issue where gravity is always off, regardless of what the display states.

**Comment by RoboMWM** [comment]
Did you disable armor stand ticking in paper config?

**Comment by RypoFalem** [comment]
I can't reproduce in the latest version of paper

**Comment by RypoFalem** [comment]
Gonna assume it was just an issue with the server software that's now fixed. Lemme know if this isn't the case!
