### ISSUE TITLE
Defective since 1.16.1

### ISSUE THREAD

**Issue by Blueeyestar** [RypoFalem/ArmorStandEditor#26]
Unfortunately, the plugin has been unusable since the 1.16.1 update. Actions can no longer be carried out. I hope that someone can save the plugin.

**Comment by RoboMWM** [comment]
Wasn't 1.16 released only a few days ago?

**Comment by Blueeyestar** [comment]
Yes, but they added 1.16.1 a day later because the realms were unstable.

**Comment by RoboMWM** [comment]
Ok
So he acknowledged 1.16 in the spigot thread.

So there's no need to hope someone will "save" the plugin

**Comment by RypoFalem** [comment]
Be patient please :)
