### ISSUE TITLE
Untraceable stealing with editor tool

### ISSUE THREAD

**Issue by Benlier** [RypoFalem/ArmorStandEditor#37]
I want to allow my players to use the armor stand editor to liven up their RP.

The problem is that they can access the equipment on any armor stand and retrieve the contents with no way of tracing that this happened with plugins like coreprotect (that I am aware of).

Possible solutions:

1. adding a permission check for accessing equipment with the editor tool. (downside is not all items can be set in the head slot without the permission)

2. Implementing an ownership system as described in #36

**Comment by Benlier** [comment]
@RypoFalem made a benign PR that fixes this issue. Feel free to use it <3

**Comment by RSNFreud** [comment]
@Benlier Does this fix the fact that the plugin doesnt respect towny perms anymore as well?

**Comment by Benlier** [comment]
> @Benlier Does this fix the fact that the plugin doesnt respect towny perms anymore as well?

No, this issue has nothing to do with towny.
