### ISSUE TITLE
Ability to change ArmorStand name from GUI.

### ISSUE THREAD

**Issue by mibby** [RypoFalem/ArmorStandEditor#5]
Would it be possible to redesign the GUI to allow for an armorstand's displayname to be changed / customized? Similarly to this plugin. https://www.spigotmc.org/resources/armor-stand-tools.2237/

**Comment by RypoFalem** [comment]
It is possible. Use a nametag on the armorstand in the same way you would use it on a mob. Formatting codes such as bold and color codes are also supported - just use & instead of §.
